"""empty message

Revision ID: a7b0c0af25c0
Revises: 8b1b7e4740cb
Create Date: 2020-01-05 21:07:03.529045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b0c0af25c0'
down_revision = '8b1b7e4740cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wishes_name_owner_id_key', 'wishes', type_='unique')
    op.create_unique_constraint(None, 'wishes', ['name', 'owner_id', 'is_active'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishes', type_='unique')
    op.create_unique_constraint('wishes_name_owner_id_key', 'wishes', ['name', 'owner_id'])
    # ### end Alembic commands ###
